### ISSUE TITLE
Conan package development

### ISSUE THREAD

**Issue by saukijan** [Pro/mdnsd#17]
Hey @Pro, 

Do you mind if I develop Conan package for your repository and release it as a part of [conan-center-index](https://github.com/conan-io/conan-center-index) repository? 

I am developing an [open62541](https://github.com/open62541/open62541) conan package and it requires your project as a dependency (you can find my PR at [conan-center-index pull requests](https://github.com/conan-io/conan-center-index/pull/1687) for reference), I already developed a workaround method to get your project as part of open62541 repository, however conan-center-index maintainers would like my workaround to be implemented as a proper dependency, which means your project needs to be part of conan-center-index if it is to be done at all.

**Comment by Pro** [comment]
Yeah, of course, thanks for your work!
Feel free to create a conan package of this repo.

**Comment by saukijan** [comment]
It seems I was a bit premature by closing this issue. 

To create a conan package I need a version number for your latest commit: 4bd993e. Do you plan to create a release for it? If not, what versioning scheme would you prefer? 

I could use something like **v0.8.0-RC**, or **v0.7.1-RC**, etc... I am not sure of the scope of the changes since your initial release, and this would help me out with the packaging.

**Comment by Pro** [comment]
Done.
See: https://github.com/Pro/mdnsd/tree/v0.8

**Comment by saukijan** [comment]
Thank you!
